# Generated by Django 5.0.4 on 2024-11-04 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кофейни')),
                ('schedule', models.CharField(max_length=100, verbose_name='График работы')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coffeehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.coffeehouse')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('unit', models.CharField(choices=[('ml', 'мл'), ('l', 'л'), ('gr', 'гр'), ('кг', 'kg')], max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='media/img')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_house.menu')),
            ],
        ),
    ]
